
version: '3.2'
services:
  postgres:
    image: postgres:9-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  demo:
    image: demo

    command: java -Dspring.profiles.active=dev -jar /demo/demo.jar
    depends_on:
      - postgres
    ports:
      - 8050:8080
    environment:
      - POSTGRES_JDBC_URL=jdbc:postgresql://postgres:5432/test1?autoReconnect=true&useSSL=false
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    build:
      context: "./"
      dockerfile: "Dockerfile"




#  # APP**
#  web:

#    build: .
#    environment:
#      - POSTGRES_JDBC_URL=jdbc:postgresql://postgres:5432/test1
#      - POSTGRES_HOST=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres

#    expose:
#      - '8080'
#    ports:
#      - '8080:8080'
